### ISSUE TITLE
add namespace to resources 

### ISSUE THREAD

**Issue by dkrzyszczyk** [treactor/treactor-helm#1]
Description of the problem:

If you want to run ```helm install main . -n=treactor --values values-local.yaml``` successfully you need `treactor` namespace to be present. But when you create if before `install` command with `kubectl apply -f templates/namespace.yaml` then it still shows you error: 

_Error: rendered manifests contain a resource that already exists. Unable to continue with install: Namespace "treactor" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation e
rror: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "main"; annotation validation error: missing key "meta.helm.sh/release-namespace
": must be set to "treactor"_

**So you have to:** 

- create tractor namespace
- remove namespace.yaml from helm resources
- then run install command

**Comment by alexvanboxel** [comment]
You can now use options: createNamespace=false
